CREATE SCHEMA `project-app`;
USE `project-app`;

CREATE TABLE `project-app`.`books` (
  bookID VARCHAR(255) PRIMARY KEY NOT NULL ,
  bookTitle VARCHAR(255) NOT NULL,
  authorName VARCHAR(255) NOT NULL,
  bookDescription VARCHAR(2500) DEFAULT NULL,
  imageURL VARCHAR(255) DEFAULT NULL,
  category VARCHAR(255) NOT NULL,
  bookPDFURL VARCHAR(255) DEFAULT NULL,
  bookPrice VARCHAR(255) NOT NULL
);
